// Copies the third-party runtime files out of node_modules into src/, so the
// project runs with no network. Re-run with `npm run vendor` after changing a
// version in package.json. The copied files are committed to git.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const nm = p => join(root, 'node_modules', p);
mkdirSync(join(root, 'src/vendor'), { recursive: true });
mkdirSync(join(root, 'src/fonts'), { recursive: true });

copyFileSync(nm('lucide/dist/umd/lucide.min.js'), join(root, 'src/vendor/lucide.min.js'));
copyFileSync(nm('three/build/three.min.js'), join(root, 'src/vendor/three.min.js'));

// The same faces the page asked Google Fonts for:
// Lato 400, 700, 900, 900 italic and JetBrains Mono 400, 500, 700.
const faces = [
  ['lato', 'Lato', 400, 'normal'], ['lato', 'Lato', 700, 'normal'], ['lato', 'Lato', 900, 'normal'], ['lato', 'Lato', 900, 'italic'],
  ['jetbrains-mono', 'JetBrains Mono', 400, 'normal'], ['jetbrains-mono', 'JetBrains Mono', 500, 'normal'], ['jetbrains-mono', 'JetBrains Mono', 700, 'normal']
];
const subsets = ['latin-ext', 'latin'];
let css = '/* Generated by scripts/vendor.mjs. Fonts are local files, no network. */\n';
for (const [pkg, family, weight, style] of faces) {
  const sheet = readFileSync(nm(`@fontsource/${pkg}/${weight}${style === 'italic' ? '-italic' : ''}.css`), 'utf8');
  for (const subset of subsets) {
    const id = `${pkg}-${subset}-${weight}-${style}`;
    const block = sheet.split('/* ' + id + ' */')[1];
    const range = block && block.match(/unicode-range:\s*([^;]+);/);
    if (!range) throw new Error('No unicode-range found for ' + id);
    copyFileSync(nm(`@fontsource/${pkg}/files/${id}.woff2`), join(root, 'src/fonts', id + '.woff2'));
    css += `@font-face { font-family: '${family}'; font-style: ${style}; font-weight: ${weight}; font-display: swap; src: url(fonts/${id}.woff2) format('woff2'); unicode-range: ${range[1]}; }\n`;
  }
}
writeFileSync(join(root, 'src/fonts.css'), css);
console.log('Vendored lucide, three and', faces.length * subsets.length, 'font files into src/');
